[tools]
go = "1.27"
"aqua:golangci/golangci-lint" = "2.13"

[tasks.setup]
description = "Setup environment"
run = "rm -rf ./.git/hooks && ln -sfF $(pwd)/.githooks $(pwd)/.git/hooks"

[tasks.build]
description = "Build packages"
run = "go build ./..."

[tasks.test]
description = "Run tests"
run = "go test -timeout 1m ./..."

[tasks.testrace]
description = "Run tests with race detector enabled"
run = "go test -timeout 1m -race ./..."

[tasks.fuzz]
description = "Fuzz test code"
run = [
  "go test -timeout 1m -fuzztime 1m -fuzz FuzzEmbeddedDB"
]

[tasks.bench]
description = "Benchmark code"
run = "go test -skip '(Test|Fuzz).*' -count 6 -benchmem -bench . ./..."

[tasks.benchstat]
description = "Compute statistics for benchmark results"
run = "go tool benchstat"

[tasks.lint]
description = "Lint code"
run = "golangci-lint run"
